version: '3'

services:

  app:
    image: quay.io/keycloak/keycloak:21.1
    container_name: micro-auth-app
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_ADDR=db
      - DB_PORT=3306
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://db:3306/keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=admin
      - KC_HOSTNAME=localhost

    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    container_name: micro-auth-db
    build: ./.docker/mysql
    restart: always
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=micro_auth
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_USER_PASSWORD=admin
